/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SecuriteImport } from './routes/securite'
import { Route as MotDePasseOublieImport } from './routes/mot-de-passe-oublie'
import { Route as MonCompteImport } from './routes/mon-compte'
import { Route as MentionsLegalesImport } from './routes/mentions-legales'
import { Route as ErreurImport } from './routes/erreur'
import { Route as DonneesPersonnellesImport } from './routes/donnees-personnelles'
import { Route as DeconnexionImport } from './routes/deconnexion'
import { Route as ConnexionImport } from './routes/connexion'
import { Route as AssistanceImport } from './routes/assistance'
import { Route as AccessibiliteImport } from './routes/accessibilite'
import { Route as SurveyImport } from './routes/$survey'
import { Route as IndexImport } from './routes/index'
import { Route as MesEnquetesIndexImport } from './routes/mes-enquetes/index'
import { Route as MesEnquetesSurveyImport } from './routes/mes-enquetes/$survey'
import { Route as MesEnquetesSurveyIndexImport } from './routes/mes-enquetes/$survey/index'
import { Route as MesEnquetesSurveyUtilisationReponseImport } from './routes/mes-enquetes/$survey/utilisation-reponse'
import { Route as MesEnquetesSurveyResultatsImport } from './routes/mes-enquetes/$survey/resultats'
import { Route as MesEnquetesSurveyLoginImport } from './routes/mes-enquetes/$survey/login'
import { Route as MesEnquetesSurveyIntroductionImport } from './routes/mes-enquetes/$survey/introduction'
import { Route as MesEnquetesSurveyFaqImport } from './routes/mes-enquetes/$survey/faq'
import { Route as MesEnquetesSurveyDocumentsImport } from './routes/mes-enquetes/$survey/documents'
import { Route as MesEnquetesSurveyCadreJuridiqueImport } from './routes/mes-enquetes/$survey/cadre-juridique'
import { Route as MesEnquetesSurveyContacterAssistanceIndexImport } from './routes/mes-enquetes/$survey/contacter-assistance/index'
import { Route as MesEnquetesSurveyRepondantMailImport } from './routes/mes-enquetes/$survey/repondant/mail'
import { Route as MesEnquetesSurveyContacterAssistanceErreurImport } from './routes/mes-enquetes/$survey/contacter-assistance/erreur'
import { Route as MesEnquetesSurveyContacterAssistanceAuthImport } from './routes/mes-enquetes/$survey/contacter-assistance/auth'

// Create/Update Routes

const SecuriteRoute = SecuriteImport.update({
  id: '/securite',
  path: '/securite',
  getParentRoute: () => rootRoute,
} as any)

const MotDePasseOublieRoute = MotDePasseOublieImport.update({
  id: '/mot-de-passe-oublie',
  path: '/mot-de-passe-oublie',
  getParentRoute: () => rootRoute,
} as any)

const MonCompteRoute = MonCompteImport.update({
  id: '/mon-compte',
  path: '/mon-compte',
  getParentRoute: () => rootRoute,
} as any)

const MentionsLegalesRoute = MentionsLegalesImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRoute,
} as any)

const ErreurRoute = ErreurImport.update({
  id: '/erreur',
  path: '/erreur',
  getParentRoute: () => rootRoute,
} as any)

const DonneesPersonnellesRoute = DonneesPersonnellesImport.update({
  id: '/donnees-personnelles',
  path: '/donnees-personnelles',
  getParentRoute: () => rootRoute,
} as any)

const DeconnexionRoute = DeconnexionImport.update({
  id: '/deconnexion',
  path: '/deconnexion',
  getParentRoute: () => rootRoute,
} as any)

const ConnexionRoute = ConnexionImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRoute,
} as any)

const AssistanceRoute = AssistanceImport.update({
  id: '/assistance',
  path: '/assistance',
  getParentRoute: () => rootRoute,
} as any)

const AccessibiliteRoute = AccessibiliteImport.update({
  id: '/accessibilite',
  path: '/accessibilite',
  getParentRoute: () => rootRoute,
} as any)

const SurveyRoute = SurveyImport.update({
  id: '/$survey',
  path: '/$survey',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const MesEnquetesIndexRoute = MesEnquetesIndexImport.update({
  id: '/mes-enquetes/',
  path: '/mes-enquetes/',
  getParentRoute: () => rootRoute,
} as any)

const MesEnquetesSurveyRoute = MesEnquetesSurveyImport.update({
  id: '/mes-enquetes/$survey',
  path: '/mes-enquetes/$survey',
  getParentRoute: () => rootRoute,
} as any)

const MesEnquetesSurveyIndexRoute = MesEnquetesSurveyIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MesEnquetesSurveyRoute,
} as any)

const MesEnquetesSurveyUtilisationReponseRoute =
  MesEnquetesSurveyUtilisationReponseImport.update({
    id: '/utilisation-reponse',
    path: '/utilisation-reponse',
    getParentRoute: () => MesEnquetesSurveyRoute,
  } as any)

const MesEnquetesSurveyResultatsRoute = MesEnquetesSurveyResultatsImport.update(
  {
    id: '/resultats',
    path: '/resultats',
    getParentRoute: () => MesEnquetesSurveyRoute,
  } as any,
)

const MesEnquetesSurveyLoginRoute = MesEnquetesSurveyLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => MesEnquetesSurveyRoute,
} as any)

const MesEnquetesSurveyIntroductionRoute =
  MesEnquetesSurveyIntroductionImport.update({
    id: '/introduction',
    path: '/introduction',
    getParentRoute: () => MesEnquetesSurveyRoute,
  } as any)

const MesEnquetesSurveyFaqRoute = MesEnquetesSurveyFaqImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => MesEnquetesSurveyRoute,
} as any)

const MesEnquetesSurveyDocumentsRoute = MesEnquetesSurveyDocumentsImport.update(
  {
    id: '/documents',
    path: '/documents',
    getParentRoute: () => MesEnquetesSurveyRoute,
  } as any,
)

const MesEnquetesSurveyCadreJuridiqueRoute =
  MesEnquetesSurveyCadreJuridiqueImport.update({
    id: '/cadre-juridique',
    path: '/cadre-juridique',
    getParentRoute: () => MesEnquetesSurveyRoute,
  } as any)

const MesEnquetesSurveyContacterAssistanceIndexRoute =
  MesEnquetesSurveyContacterAssistanceIndexImport.update({
    id: '/contacter-assistance/',
    path: '/contacter-assistance/',
    getParentRoute: () => MesEnquetesSurveyRoute,
  } as any)

const MesEnquetesSurveyRepondantMailRoute =
  MesEnquetesSurveyRepondantMailImport.update({
    id: '/repondant/mail',
    path: '/repondant/mail',
    getParentRoute: () => MesEnquetesSurveyRoute,
  } as any)

const MesEnquetesSurveyContacterAssistanceErreurRoute =
  MesEnquetesSurveyContacterAssistanceErreurImport.update({
    id: '/contacter-assistance/erreur',
    path: '/contacter-assistance/erreur',
    getParentRoute: () => MesEnquetesSurveyRoute,
  } as any)

const MesEnquetesSurveyContacterAssistanceAuthRoute =
  MesEnquetesSurveyContacterAssistanceAuthImport.update({
    id: '/contacter-assistance/auth',
    path: '/contacter-assistance/auth',
    getParentRoute: () => MesEnquetesSurveyRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$survey': {
      id: '/$survey'
      path: '/$survey'
      fullPath: '/$survey'
      preLoaderRoute: typeof SurveyImport
      parentRoute: typeof rootRoute
    }
    '/accessibilite': {
      id: '/accessibilite'
      path: '/accessibilite'
      fullPath: '/accessibilite'
      preLoaderRoute: typeof AccessibiliteImport
      parentRoute: typeof rootRoute
    }
    '/assistance': {
      id: '/assistance'
      path: '/assistance'
      fullPath: '/assistance'
      preLoaderRoute: typeof AssistanceImport
      parentRoute: typeof rootRoute
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionImport
      parentRoute: typeof rootRoute
    }
    '/deconnexion': {
      id: '/deconnexion'
      path: '/deconnexion'
      fullPath: '/deconnexion'
      preLoaderRoute: typeof DeconnexionImport
      parentRoute: typeof rootRoute
    }
    '/donnees-personnelles': {
      id: '/donnees-personnelles'
      path: '/donnees-personnelles'
      fullPath: '/donnees-personnelles'
      preLoaderRoute: typeof DonneesPersonnellesImport
      parentRoute: typeof rootRoute
    }
    '/erreur': {
      id: '/erreur'
      path: '/erreur'
      fullPath: '/erreur'
      preLoaderRoute: typeof ErreurImport
      parentRoute: typeof rootRoute
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesImport
      parentRoute: typeof rootRoute
    }
    '/mon-compte': {
      id: '/mon-compte'
      path: '/mon-compte'
      fullPath: '/mon-compte'
      preLoaderRoute: typeof MonCompteImport
      parentRoute: typeof rootRoute
    }
    '/mot-de-passe-oublie': {
      id: '/mot-de-passe-oublie'
      path: '/mot-de-passe-oublie'
      fullPath: '/mot-de-passe-oublie'
      preLoaderRoute: typeof MotDePasseOublieImport
      parentRoute: typeof rootRoute
    }
    '/securite': {
      id: '/securite'
      path: '/securite'
      fullPath: '/securite'
      preLoaderRoute: typeof SecuriteImport
      parentRoute: typeof rootRoute
    }
    '/mes-enquetes/$survey': {
      id: '/mes-enquetes/$survey'
      path: '/mes-enquetes/$survey'
      fullPath: '/mes-enquetes/$survey'
      preLoaderRoute: typeof MesEnquetesSurveyImport
      parentRoute: typeof rootRoute
    }
    '/mes-enquetes/': {
      id: '/mes-enquetes/'
      path: '/mes-enquetes'
      fullPath: '/mes-enquetes'
      preLoaderRoute: typeof MesEnquetesIndexImport
      parentRoute: typeof rootRoute
    }
    '/mes-enquetes/$survey/cadre-juridique': {
      id: '/mes-enquetes/$survey/cadre-juridique'
      path: '/cadre-juridique'
      fullPath: '/mes-enquetes/$survey/cadre-juridique'
      preLoaderRoute: typeof MesEnquetesSurveyCadreJuridiqueImport
      parentRoute: typeof MesEnquetesSurveyImport
    }
    '/mes-enquetes/$survey/documents': {
      id: '/mes-enquetes/$survey/documents'
      path: '/documents'
      fullPath: '/mes-enquetes/$survey/documents'
      preLoaderRoute: typeof MesEnquetesSurveyDocumentsImport
      parentRoute: typeof MesEnquetesSurveyImport
    }
    '/mes-enquetes/$survey/faq': {
      id: '/mes-enquetes/$survey/faq'
      path: '/faq'
      fullPath: '/mes-enquetes/$survey/faq'
      preLoaderRoute: typeof MesEnquetesSurveyFaqImport
      parentRoute: typeof MesEnquetesSurveyImport
    }
    '/mes-enquetes/$survey/introduction': {
      id: '/mes-enquetes/$survey/introduction'
      path: '/introduction'
      fullPath: '/mes-enquetes/$survey/introduction'
      preLoaderRoute: typeof MesEnquetesSurveyIntroductionImport
      parentRoute: typeof MesEnquetesSurveyImport
    }
    '/mes-enquetes/$survey/login': {
      id: '/mes-enquetes/$survey/login'
      path: '/login'
      fullPath: '/mes-enquetes/$survey/login'
      preLoaderRoute: typeof MesEnquetesSurveyLoginImport
      parentRoute: typeof MesEnquetesSurveyImport
    }
    '/mes-enquetes/$survey/resultats': {
      id: '/mes-enquetes/$survey/resultats'
      path: '/resultats'
      fullPath: '/mes-enquetes/$survey/resultats'
      preLoaderRoute: typeof MesEnquetesSurveyResultatsImport
      parentRoute: typeof MesEnquetesSurveyImport
    }
    '/mes-enquetes/$survey/utilisation-reponse': {
      id: '/mes-enquetes/$survey/utilisation-reponse'
      path: '/utilisation-reponse'
      fullPath: '/mes-enquetes/$survey/utilisation-reponse'
      preLoaderRoute: typeof MesEnquetesSurveyUtilisationReponseImport
      parentRoute: typeof MesEnquetesSurveyImport
    }
    '/mes-enquetes/$survey/': {
      id: '/mes-enquetes/$survey/'
      path: '/'
      fullPath: '/mes-enquetes/$survey/'
      preLoaderRoute: typeof MesEnquetesSurveyIndexImport
      parentRoute: typeof MesEnquetesSurveyImport
    }
    '/mes-enquetes/$survey/contacter-assistance/auth': {
      id: '/mes-enquetes/$survey/contacter-assistance/auth'
      path: '/contacter-assistance/auth'
      fullPath: '/mes-enquetes/$survey/contacter-assistance/auth'
      preLoaderRoute: typeof MesEnquetesSurveyContacterAssistanceAuthImport
      parentRoute: typeof MesEnquetesSurveyImport
    }
    '/mes-enquetes/$survey/contacter-assistance/erreur': {
      id: '/mes-enquetes/$survey/contacter-assistance/erreur'
      path: '/contacter-assistance/erreur'
      fullPath: '/mes-enquetes/$survey/contacter-assistance/erreur'
      preLoaderRoute: typeof MesEnquetesSurveyContacterAssistanceErreurImport
      parentRoute: typeof MesEnquetesSurveyImport
    }
    '/mes-enquetes/$survey/repondant/mail': {
      id: '/mes-enquetes/$survey/repondant/mail'
      path: '/repondant/mail'
      fullPath: '/mes-enquetes/$survey/repondant/mail'
      preLoaderRoute: typeof MesEnquetesSurveyRepondantMailImport
      parentRoute: typeof MesEnquetesSurveyImport
    }
    '/mes-enquetes/$survey/contacter-assistance/': {
      id: '/mes-enquetes/$survey/contacter-assistance/'
      path: '/contacter-assistance'
      fullPath: '/mes-enquetes/$survey/contacter-assistance'
      preLoaderRoute: typeof MesEnquetesSurveyContacterAssistanceIndexImport
      parentRoute: typeof MesEnquetesSurveyImport
    }
  }
}

// Create and export the route tree

interface MesEnquetesSurveyRouteChildren {
  MesEnquetesSurveyCadreJuridiqueRoute: typeof MesEnquetesSurveyCadreJuridiqueRoute
  MesEnquetesSurveyDocumentsRoute: typeof MesEnquetesSurveyDocumentsRoute
  MesEnquetesSurveyFaqRoute: typeof MesEnquetesSurveyFaqRoute
  MesEnquetesSurveyIntroductionRoute: typeof MesEnquetesSurveyIntroductionRoute
  MesEnquetesSurveyLoginRoute: typeof MesEnquetesSurveyLoginRoute
  MesEnquetesSurveyResultatsRoute: typeof MesEnquetesSurveyResultatsRoute
  MesEnquetesSurveyUtilisationReponseRoute: typeof MesEnquetesSurveyUtilisationReponseRoute
  MesEnquetesSurveyIndexRoute: typeof MesEnquetesSurveyIndexRoute
  MesEnquetesSurveyContacterAssistanceAuthRoute: typeof MesEnquetesSurveyContacterAssistanceAuthRoute
  MesEnquetesSurveyContacterAssistanceErreurRoute: typeof MesEnquetesSurveyContacterAssistanceErreurRoute
  MesEnquetesSurveyRepondantMailRoute: typeof MesEnquetesSurveyRepondantMailRoute
  MesEnquetesSurveyContacterAssistanceIndexRoute: typeof MesEnquetesSurveyContacterAssistanceIndexRoute
}

const MesEnquetesSurveyRouteChildren: MesEnquetesSurveyRouteChildren = {
  MesEnquetesSurveyCadreJuridiqueRoute: MesEnquetesSurveyCadreJuridiqueRoute,
  MesEnquetesSurveyDocumentsRoute: MesEnquetesSurveyDocumentsRoute,
  MesEnquetesSurveyFaqRoute: MesEnquetesSurveyFaqRoute,
  MesEnquetesSurveyIntroductionRoute: MesEnquetesSurveyIntroductionRoute,
  MesEnquetesSurveyLoginRoute: MesEnquetesSurveyLoginRoute,
  MesEnquetesSurveyResultatsRoute: MesEnquetesSurveyResultatsRoute,
  MesEnquetesSurveyUtilisationReponseRoute:
    MesEnquetesSurveyUtilisationReponseRoute,
  MesEnquetesSurveyIndexRoute: MesEnquetesSurveyIndexRoute,
  MesEnquetesSurveyContacterAssistanceAuthRoute:
    MesEnquetesSurveyContacterAssistanceAuthRoute,
  MesEnquetesSurveyContacterAssistanceErreurRoute:
    MesEnquetesSurveyContacterAssistanceErreurRoute,
  MesEnquetesSurveyRepondantMailRoute: MesEnquetesSurveyRepondantMailRoute,
  MesEnquetesSurveyContacterAssistanceIndexRoute:
    MesEnquetesSurveyContacterAssistanceIndexRoute,
}

const MesEnquetesSurveyRouteWithChildren =
  MesEnquetesSurveyRoute._addFileChildren(MesEnquetesSurveyRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$survey': typeof SurveyRoute
  '/accessibilite': typeof AccessibiliteRoute
  '/assistance': typeof AssistanceRoute
  '/connexion': typeof ConnexionRoute
  '/deconnexion': typeof DeconnexionRoute
  '/donnees-personnelles': typeof DonneesPersonnellesRoute
  '/erreur': typeof ErreurRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mon-compte': typeof MonCompteRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/securite': typeof SecuriteRoute
  '/mes-enquetes/$survey': typeof MesEnquetesSurveyRouteWithChildren
  '/mes-enquetes': typeof MesEnquetesIndexRoute
  '/mes-enquetes/$survey/cadre-juridique': typeof MesEnquetesSurveyCadreJuridiqueRoute
  '/mes-enquetes/$survey/documents': typeof MesEnquetesSurveyDocumentsRoute
  '/mes-enquetes/$survey/faq': typeof MesEnquetesSurveyFaqRoute
  '/mes-enquetes/$survey/introduction': typeof MesEnquetesSurveyIntroductionRoute
  '/mes-enquetes/$survey/login': typeof MesEnquetesSurveyLoginRoute
  '/mes-enquetes/$survey/resultats': typeof MesEnquetesSurveyResultatsRoute
  '/mes-enquetes/$survey/utilisation-reponse': typeof MesEnquetesSurveyUtilisationReponseRoute
  '/mes-enquetes/$survey/': typeof MesEnquetesSurveyIndexRoute
  '/mes-enquetes/$survey/contacter-assistance/auth': typeof MesEnquetesSurveyContacterAssistanceAuthRoute
  '/mes-enquetes/$survey/contacter-assistance/erreur': typeof MesEnquetesSurveyContacterAssistanceErreurRoute
  '/mes-enquetes/$survey/repondant/mail': typeof MesEnquetesSurveyRepondantMailRoute
  '/mes-enquetes/$survey/contacter-assistance': typeof MesEnquetesSurveyContacterAssistanceIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$survey': typeof SurveyRoute
  '/accessibilite': typeof AccessibiliteRoute
  '/assistance': typeof AssistanceRoute
  '/connexion': typeof ConnexionRoute
  '/deconnexion': typeof DeconnexionRoute
  '/donnees-personnelles': typeof DonneesPersonnellesRoute
  '/erreur': typeof ErreurRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mon-compte': typeof MonCompteRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/securite': typeof SecuriteRoute
  '/mes-enquetes': typeof MesEnquetesIndexRoute
  '/mes-enquetes/$survey/cadre-juridique': typeof MesEnquetesSurveyCadreJuridiqueRoute
  '/mes-enquetes/$survey/documents': typeof MesEnquetesSurveyDocumentsRoute
  '/mes-enquetes/$survey/faq': typeof MesEnquetesSurveyFaqRoute
  '/mes-enquetes/$survey/introduction': typeof MesEnquetesSurveyIntroductionRoute
  '/mes-enquetes/$survey/login': typeof MesEnquetesSurveyLoginRoute
  '/mes-enquetes/$survey/resultats': typeof MesEnquetesSurveyResultatsRoute
  '/mes-enquetes/$survey/utilisation-reponse': typeof MesEnquetesSurveyUtilisationReponseRoute
  '/mes-enquetes/$survey': typeof MesEnquetesSurveyIndexRoute
  '/mes-enquetes/$survey/contacter-assistance/auth': typeof MesEnquetesSurveyContacterAssistanceAuthRoute
  '/mes-enquetes/$survey/contacter-assistance/erreur': typeof MesEnquetesSurveyContacterAssistanceErreurRoute
  '/mes-enquetes/$survey/repondant/mail': typeof MesEnquetesSurveyRepondantMailRoute
  '/mes-enquetes/$survey/contacter-assistance': typeof MesEnquetesSurveyContacterAssistanceIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$survey': typeof SurveyRoute
  '/accessibilite': typeof AccessibiliteRoute
  '/assistance': typeof AssistanceRoute
  '/connexion': typeof ConnexionRoute
  '/deconnexion': typeof DeconnexionRoute
  '/donnees-personnelles': typeof DonneesPersonnellesRoute
  '/erreur': typeof ErreurRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mon-compte': typeof MonCompteRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/securite': typeof SecuriteRoute
  '/mes-enquetes/$survey': typeof MesEnquetesSurveyRouteWithChildren
  '/mes-enquetes/': typeof MesEnquetesIndexRoute
  '/mes-enquetes/$survey/cadre-juridique': typeof MesEnquetesSurveyCadreJuridiqueRoute
  '/mes-enquetes/$survey/documents': typeof MesEnquetesSurveyDocumentsRoute
  '/mes-enquetes/$survey/faq': typeof MesEnquetesSurveyFaqRoute
  '/mes-enquetes/$survey/introduction': typeof MesEnquetesSurveyIntroductionRoute
  '/mes-enquetes/$survey/login': typeof MesEnquetesSurveyLoginRoute
  '/mes-enquetes/$survey/resultats': typeof MesEnquetesSurveyResultatsRoute
  '/mes-enquetes/$survey/utilisation-reponse': typeof MesEnquetesSurveyUtilisationReponseRoute
  '/mes-enquetes/$survey/': typeof MesEnquetesSurveyIndexRoute
  '/mes-enquetes/$survey/contacter-assistance/auth': typeof MesEnquetesSurveyContacterAssistanceAuthRoute
  '/mes-enquetes/$survey/contacter-assistance/erreur': typeof MesEnquetesSurveyContacterAssistanceErreurRoute
  '/mes-enquetes/$survey/repondant/mail': typeof MesEnquetesSurveyRepondantMailRoute
  '/mes-enquetes/$survey/contacter-assistance/': typeof MesEnquetesSurveyContacterAssistanceIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$survey'
    | '/accessibilite'
    | '/assistance'
    | '/connexion'
    | '/deconnexion'
    | '/donnees-personnelles'
    | '/erreur'
    | '/mentions-legales'
    | '/mon-compte'
    | '/mot-de-passe-oublie'
    | '/securite'
    | '/mes-enquetes/$survey'
    | '/mes-enquetes'
    | '/mes-enquetes/$survey/cadre-juridique'
    | '/mes-enquetes/$survey/documents'
    | '/mes-enquetes/$survey/faq'
    | '/mes-enquetes/$survey/introduction'
    | '/mes-enquetes/$survey/login'
    | '/mes-enquetes/$survey/resultats'
    | '/mes-enquetes/$survey/utilisation-reponse'
    | '/mes-enquetes/$survey/'
    | '/mes-enquetes/$survey/contacter-assistance/auth'
    | '/mes-enquetes/$survey/contacter-assistance/erreur'
    | '/mes-enquetes/$survey/repondant/mail'
    | '/mes-enquetes/$survey/contacter-assistance'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$survey'
    | '/accessibilite'
    | '/assistance'
    | '/connexion'
    | '/deconnexion'
    | '/donnees-personnelles'
    | '/erreur'
    | '/mentions-legales'
    | '/mon-compte'
    | '/mot-de-passe-oublie'
    | '/securite'
    | '/mes-enquetes'
    | '/mes-enquetes/$survey/cadre-juridique'
    | '/mes-enquetes/$survey/documents'
    | '/mes-enquetes/$survey/faq'
    | '/mes-enquetes/$survey/introduction'
    | '/mes-enquetes/$survey/login'
    | '/mes-enquetes/$survey/resultats'
    | '/mes-enquetes/$survey/utilisation-reponse'
    | '/mes-enquetes/$survey'
    | '/mes-enquetes/$survey/contacter-assistance/auth'
    | '/mes-enquetes/$survey/contacter-assistance/erreur'
    | '/mes-enquetes/$survey/repondant/mail'
    | '/mes-enquetes/$survey/contacter-assistance'
  id:
    | '__root__'
    | '/'
    | '/$survey'
    | '/accessibilite'
    | '/assistance'
    | '/connexion'
    | '/deconnexion'
    | '/donnees-personnelles'
    | '/erreur'
    | '/mentions-legales'
    | '/mon-compte'
    | '/mot-de-passe-oublie'
    | '/securite'
    | '/mes-enquetes/$survey'
    | '/mes-enquetes/'
    | '/mes-enquetes/$survey/cadre-juridique'
    | '/mes-enquetes/$survey/documents'
    | '/mes-enquetes/$survey/faq'
    | '/mes-enquetes/$survey/introduction'
    | '/mes-enquetes/$survey/login'
    | '/mes-enquetes/$survey/resultats'
    | '/mes-enquetes/$survey/utilisation-reponse'
    | '/mes-enquetes/$survey/'
    | '/mes-enquetes/$survey/contacter-assistance/auth'
    | '/mes-enquetes/$survey/contacter-assistance/erreur'
    | '/mes-enquetes/$survey/repondant/mail'
    | '/mes-enquetes/$survey/contacter-assistance/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SurveyRoute: typeof SurveyRoute
  AccessibiliteRoute: typeof AccessibiliteRoute
  AssistanceRoute: typeof AssistanceRoute
  ConnexionRoute: typeof ConnexionRoute
  DeconnexionRoute: typeof DeconnexionRoute
  DonneesPersonnellesRoute: typeof DonneesPersonnellesRoute
  ErreurRoute: typeof ErreurRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  MonCompteRoute: typeof MonCompteRoute
  MotDePasseOublieRoute: typeof MotDePasseOublieRoute
  SecuriteRoute: typeof SecuriteRoute
  MesEnquetesSurveyRoute: typeof MesEnquetesSurveyRouteWithChildren
  MesEnquetesIndexRoute: typeof MesEnquetesIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SurveyRoute: SurveyRoute,
  AccessibiliteRoute: AccessibiliteRoute,
  AssistanceRoute: AssistanceRoute,
  ConnexionRoute: ConnexionRoute,
  DeconnexionRoute: DeconnexionRoute,
  DonneesPersonnellesRoute: DonneesPersonnellesRoute,
  ErreurRoute: ErreurRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  MonCompteRoute: MonCompteRoute,
  MotDePasseOublieRoute: MotDePasseOublieRoute,
  SecuriteRoute: SecuriteRoute,
  MesEnquetesSurveyRoute: MesEnquetesSurveyRouteWithChildren,
  MesEnquetesIndexRoute: MesEnquetesIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$survey",
        "/accessibilite",
        "/assistance",
        "/connexion",
        "/deconnexion",
        "/donnees-personnelles",
        "/erreur",
        "/mentions-legales",
        "/mon-compte",
        "/mot-de-passe-oublie",
        "/securite",
        "/mes-enquetes/$survey",
        "/mes-enquetes/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$survey": {
      "filePath": "$survey.tsx"
    },
    "/accessibilite": {
      "filePath": "accessibilite.tsx"
    },
    "/assistance": {
      "filePath": "assistance.tsx"
    },
    "/connexion": {
      "filePath": "connexion.tsx"
    },
    "/deconnexion": {
      "filePath": "deconnexion.tsx"
    },
    "/donnees-personnelles": {
      "filePath": "donnees-personnelles.tsx"
    },
    "/erreur": {
      "filePath": "erreur.tsx"
    },
    "/mentions-legales": {
      "filePath": "mentions-legales.tsx"
    },
    "/mon-compte": {
      "filePath": "mon-compte.tsx"
    },
    "/mot-de-passe-oublie": {
      "filePath": "mot-de-passe-oublie.tsx"
    },
    "/securite": {
      "filePath": "securite.tsx"
    },
    "/mes-enquetes/$survey": {
      "filePath": "mes-enquetes/$survey.tsx",
      "children": [
        "/mes-enquetes/$survey/cadre-juridique",
        "/mes-enquetes/$survey/documents",
        "/mes-enquetes/$survey/faq",
        "/mes-enquetes/$survey/introduction",
        "/mes-enquetes/$survey/login",
        "/mes-enquetes/$survey/resultats",
        "/mes-enquetes/$survey/utilisation-reponse",
        "/mes-enquetes/$survey/",
        "/mes-enquetes/$survey/contacter-assistance/auth",
        "/mes-enquetes/$survey/contacter-assistance/erreur",
        "/mes-enquetes/$survey/repondant/mail",
        "/mes-enquetes/$survey/contacter-assistance/"
      ]
    },
    "/mes-enquetes/": {
      "filePath": "mes-enquetes/index.tsx"
    },
    "/mes-enquetes/$survey/cadre-juridique": {
      "filePath": "mes-enquetes/$survey/cadre-juridique.tsx",
      "parent": "/mes-enquetes/$survey"
    },
    "/mes-enquetes/$survey/documents": {
      "filePath": "mes-enquetes/$survey/documents.tsx",
      "parent": "/mes-enquetes/$survey"
    },
    "/mes-enquetes/$survey/faq": {
      "filePath": "mes-enquetes/$survey/faq.tsx",
      "parent": "/mes-enquetes/$survey"
    },
    "/mes-enquetes/$survey/introduction": {
      "filePath": "mes-enquetes/$survey/introduction.tsx",
      "parent": "/mes-enquetes/$survey"
    },
    "/mes-enquetes/$survey/login": {
      "filePath": "mes-enquetes/$survey/login.tsx",
      "parent": "/mes-enquetes/$survey"
    },
    "/mes-enquetes/$survey/resultats": {
      "filePath": "mes-enquetes/$survey/resultats.tsx",
      "parent": "/mes-enquetes/$survey"
    },
    "/mes-enquetes/$survey/utilisation-reponse": {
      "filePath": "mes-enquetes/$survey/utilisation-reponse.tsx",
      "parent": "/mes-enquetes/$survey"
    },
    "/mes-enquetes/$survey/": {
      "filePath": "mes-enquetes/$survey/index.tsx",
      "parent": "/mes-enquetes/$survey"
    },
    "/mes-enquetes/$survey/contacter-assistance/auth": {
      "filePath": "mes-enquetes/$survey/contacter-assistance/auth.tsx",
      "parent": "/mes-enquetes/$survey"
    },
    "/mes-enquetes/$survey/contacter-assistance/erreur": {
      "filePath": "mes-enquetes/$survey/contacter-assistance/erreur.tsx",
      "parent": "/mes-enquetes/$survey"
    },
    "/mes-enquetes/$survey/repondant/mail": {
      "filePath": "mes-enquetes/$survey/repondant/mail.tsx",
      "parent": "/mes-enquetes/$survey"
    },
    "/mes-enquetes/$survey/contacter-assistance/": {
      "filePath": "mes-enquetes/$survey/contacter-assistance/index.tsx",
      "parent": "/mes-enquetes/$survey"
    }
  }
}
ROUTE_MANIFEST_END */
